defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

compute:
  ngpus: 1
  nodes: 1

logging:
  log_freq: 100
  log_lr_every: ${logging.log_freq}
  log_file_name: stdout.log
  enable_wandb: True
  entity: mattias421
  project: flow_matching
  group: null

data:
  text: librispeech_lm
  valid: librispeech_lm
  cache_dir: /path/to/cache/dir
  features_path: /store/store4/data/LibriSpeech-Clean-NoSil/features/mimi/8hr/
  num_workers: 0
  max_decode_ratio: 1
  debug: false
  codec_name: mimi # [focalcodec, mimi]
  train_percent: 50
  supervised: True
  text_tokenizer: speecht5

training:
  batch_size: 32
  snapshot: 500
  eval_freq: 500
  perplexity_freq: 50000000
  cer_freq: 5000
  seed: 42
  unsupervised_prob: 1
  partial_loss_weight: 1
  uncond_warmup: 500
  pad_weight: 1.0
  codebook_prob: 0.3

eval:
  batch_size: 8
  sample_batch_size: 8
  perplexity: True
  perplexity_batch_size: 16
  n_gen_iter: 8
  kenlm_path: /path/to/kenlm
  cfg_strength: 1.0
  inference_block: 1

optim:
  weight_decay: 0.03
  optimizer: AdamW
  lr: 1e-4
  beta1: 0.9
  beta2: 0.95
  eps: 1e-8
  warmup: 500
  grad_clip: 1.
  eta_min_ratio: 0.1
  fused: false
  n_iters: 100000
  log_lr_every: ${logging.log_lr_every}
  source_soft_update_weight: 1.0
  loss_speech_weight: 0.5

flow:
  source_distribution: mask # [uniform, mask]
  loss_function: generalized_kl  # [cross_entropy, generalized_kl]
  exponent: 1.
  scheduler_type: polynomial
  sampling_steps: 64
  partial_noise_prob: 0

model:
  hidden_size: 768
  cond_dim: 128
  length: 512
  n_blocks: 2
  n_heads: 12
  dropout: 0.0
  compile: false
  vocab_size_speech: 2048
  n_quantizers: 100

hydra_dir: /path/to/hydra/dir

hydra:
  run:
    dir: ${hydra_dir}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ${hydra_dir}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 4320
    partition: gpu,gpu-h100,gpu-h100-nvl
    qos: gpu:1
    gpus_per_node: ${compute.ngpus}
    cpus_per_task: 8
    mem_gb: null
    mem_per_cpu: null
    mem_per_gpu: null
    srun_args:
        - --export=ALL
    setup:
        - ml binutils GCCcore GCC libsndfile cuDNN bzip2
        - source .venv/bin/activate
