defaults:
  - _self_

compute:
  ngpus: 1
  nodes: 1

logging:
  log_freq: 100
  log_lr_every: ${logging.log_freq}
  log_file_name: stdout.log
  enable_wandb: True
  entity: mattias421
  project: flow_matching
  group: null

data:
  text_data: /store/store4/data/variety-text-corpus/LibriLM/text/phones/
  features_path: /store/store4/data/LibriSpeech-10hr-rVAD/features/wav2vec_vox/
  num_workers: 0
  max_decode_ratio: 1
  debug: false
  codec_name: mimi # [focalcodec, mimi]
  train_percent: 50
  supervised: True
  text_tokenizer: speecht5

training:
  batch_size: 16
  snapshot: 500
  eval_freq: 5000
  perplexity_freq: 50000000
  cer_freq: 100
  seed: 42
  unsupervised_prob: 1
  partial_loss_weight: 1
  uncond_warmup: 500
  pad_weight: 1.0
  codebook_prob: 0.0
  time_conditioning: true

eval:
  batch_size: 8
  sample_batch_size: 8
  perplexity: True
  perplexity_batch_size: 16
  n_gen_iter: 8
  kenlm_path: /path/to/kenlm
  cfg_strength: 1.0
  inference_block: 1

optim:
  weight_decay: 0.03
  optimizer: AdamW
  lr: 1e-3
  beta1: 0.9
  beta2: 0.95
  eps: 1e-8
  warmup: 500
  grad_clip: 1.
  eta_min_ratio: 0.1
  fused: false
  n_iters: 100000
  log_lr_every: ${logging.log_lr_every}
  source_soft_update_weight: 1.0
  loss_speech_weight: 0.5

flow:
  source_distribution: mask # [uniform, mask]
  loss_function: generalized_kl  # [cross_entropy, generalized_kl]
  exponent: 1.
  scheduler_type: polynomial
  sampling_steps: 64
  partial_noise_prob: 0

model:
  hidden_size: 768
  cond_dim: 128
  length: 1024
  n_blocks: 2
  n_heads: 12
  dropout: 0.0
  compile: false
  vocab_size_speech: 64
  n_quantizers: 64
  quantizer_groups: 1
  generator_stride: 3
  generator_kernel: 9
  generator_bias: false
  generator_batch_norm: 30
  generator_residual: true
  generator_pad: -1
  generator_dilation: 1
  feature_size: 1024
  segmentation:
    type: JOIN
    mean_pool: true
    mean_pool_join: false
    remove_zeros: false
    subsample_rate: 0.25

hydra_dir: /path/to/hydra/dir

hydra:
  run:
    dir: ${hydra_dir}/${now:%Y.%m.%d}/${now:%H%M%S}
