defaults:
  - _self_
  - override hydra/sweeper/sampler: random
  - override hydra/launcher: submitit_slurm
  - override hydra/sweeper: optuna

study_name: default

compute:
  ngpus: 1
  nodes: 1

logging:
  log_freq: 100
  log_lr_every: ${logging.log_freq}
  log_file_name: stdout.log
  enable_wandb: True
  entity: mattias421
  project: flow_matching
  group: null

data:
  train: librispeech
  audio: librispeech
  text: librispeech
  valid: librispeech
  cache_dir: /path/to/cache/dir
  num_workers: 8
  debug: false
  codec_name: mimi # [focalcodec, mimi]
  train_percent: 100
  supervised: True

training:
  batch_size: 64
  snapshot: 500
  eval_freq: 500
  perplexity_freq: 5000000
  cer_freq: 5000
  seed: 42
  partial_loss_weight: 1
  uncond_warmup: 10000
  pad_weight: 1.0

eval:
  batch_size: 32
  sample_batch_size: 16
  perplexity: True
  perplexity_batch_size: 128
  n_gen_iter: 8
  kenlm_path: /path/to/kenlm

optim:
  weight_decay: 0.0007
  optimizer: AdamW
  lr: 4e-4
  beta1: 0.9
  beta2: 0.95
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.
  eta_min_ratio: 0.1
  fused: false
  n_iters: 100000
  log_lr_every: ${logging.log_lr_every}
  source_soft_update_weight: 0.05
  loss_speech_weight: 0.25

flow:
  source_distribution: asr  # [asr]
  loss_function: cross_entropy  # [cross_entropy, generalized_kl]
  exponent: 1.
  scheduler_type: polynomial
  sampling_steps: 64
  partial_noise_prob: 0

model:
  hidden_size: 768
  cond_dim: 128
  length: 128
  n_blocks: 4
  n_heads: 12
  dropout: 0.1
  compile: false
  whisper_dim: 768

hydra_dir: /path/to/hydra/dir

hydra:
  run:
    dir: ${hydra_dir}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ${hydra_dir}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 4320
    partition: gpu,gpu-h100,gpu-h100-nvl
    qos: gpu:1
    gpus_per_node: ${compute.ngpus}
    cpus_per_task: 8
    mem_gb: null
    mem_per_cpu: null
    mem_per_gpu: null
    srun_args:
        - --export=ALL
    setup:
        - export WANDB_TAGS="${study_name}"
        - ml binutils GCCcore GCC libsndfile cuDNN bzip2
        - source .venv/bin/activate
  sweeper:
    sampler:
      seed: ${training.seed}
    direction: minimize
    study_name: ${study_name}
    # storage: null
    n_trials: 36
    n_jobs: 12
    # max_failure_rate: 0.5
    params:
        optim.lr: tag(log, interval(0.0001, 0.0005))
        optim.warmup: choice(250,500,1000,1500,2000)


