[project]
name = "text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets==3.6.0",
    "einops>=0.8.1",
    "fairseq==0.12.2",
    "flow-matching>=1.0.10",
    "hydra-submitit-launcher>=1.1.1",
    "jiwer>=4.0.0",
    "joblib>=1.5.2",
    "kenlm>=0.3.0",
    "librosa>=0.11.0",
    "npy-append-array>=0.9.19",
    "numpy==1.26.4",
    "omegaconf>=2.0.6",
    "pandas==2.0.0",
    "pyarrow==19.0.0",
    "sentencepiece>=0.2.1",
    "setuptools>=80.9.0",
    "soundfile>=0.13.1",
    "speechtokenizer>=1.0.1",
    "tensorboardx>=2.6.4",
    "torch==2.5.0",
    "transformers>=4.57.1",
    "wandb>=0.22.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.5",
]
